name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and Lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript check
      run: npm run type-check

    - name: Run ESLint
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Run MCP tests
      run: |
        # Start the dev server in background
        npm run dev &
        DEV_PID=$!
        
        # Wait for server to start
        echo "Waiting for server to start..."
        sleep 15
        
        # Run MCP tests
        node scripts/test-mcp.js --url=http://localhost:3000 --api-key=test-key --mac=84:94:37:e4:24:88 --verbose=false
        
        # Kill the dev server
        kill $DEV_PID

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: Deploy to Vercel
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'

    - name: Test production deployment
      run: |
        sleep 30  # Wait for deployment to be ready
        node scripts/test-mcp.js --url=${{ secrets.VERCEL_PROD_URL }} --api-key=${{ secrets.API_KEY }} --mac=${{ secrets.MAC_ADDRESS }} --verbose=false